from datetime import datetime

class ReportAgent:
    def generate_report(self, gender, inputs, analysis, explanation, context):
        """
        Creates a clean Markdown/Text report.
        """
        
        report = f"""
==================================================
           LABWISE AI - MEDICAL REPORT
==================================================
Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}
Patient Gender: {gender}

[INPUT VALUES]
--------------------------------------------------
- Hemoglobin: {inputs['hb']} g/dL
- WBC: {inputs['wbc']} /mcL
- Platelets: {inputs['platelets']} /mcL

[ANALYSIS RESULTS]
--------------------------------------------------
> Hemoglobin: {analysis['hb']['status']} ({analysis['hb']['severity']})
> WBC: {analysis['wbc']['status']} ({analysis['wbc']['severity']})
> Platelets: {analysis['platelets']['status']} ({analysis['platelets']['severity']})

[EXPLANATION (DARIJA)]
--------------------------------------------------
{explanation}

[MEDICAL CONTEXT (REFERENCE)]
--------------------------------------------------
{context}

[DISCLAIMER]
--------------------------------------------------
This report is generated by an AI prototype for awareness purposes only.
IT IS NOT A MEDICAL DIAGNOSIS.
Please consult a qualified doctor for interpretation.
==================================================
"""
        return report
